/*
TASK:
  case ACTION.CANDIDATE_YES_NO:
  case ACTION.CARS_FOR_REFUEL:
  case ACTION.GIVE_OUT_FUEL:
  case ACTION.ADD_NEW_DRIVER_TO_DB:
  case ACTION.INFO_ABOUT_CAR:
  case ACTION.INFO_ABOUT_DRIVER:
  case ACTION.CAR_STATISTIC:
  case ACTION.GET_LIST_OF_YEARS:
  case ACTION.GET_STATS_FOR_MONTH:
*/
